

data_folder: "/folder/to/data/"
key_file_path: "/00_Extra/Details_imaging_data_3D.xls"
image_file_path_2D: "/03_Preprocessed_Data/01_2D/"
image_file_path_3D: "/03_Preprocessed_Data/02_3D/"
output_folder: "/folder/to/output/"




channel_tumor : 0
channel_macrophages: 1
channel_vessels: 2


# Filters for tumor and vascular segmentation

## rolling ball background substraction

substract_background: "None" # "rolling_ball", "ellipsoid_kernel" or "None" to skip background substraction
ellipsoid_kernel_size: 5
ellipsoid_kernel_intensity: 5


## anisotropic Gaussian blur, not that sigma is a scaling factor here, which is multiplied by the pixel size PhysicalSizeX,Y,Z to obtain the "physical" anisotropic sigma

sigma_macrophage: 10  # sigma for Gaussian filtering before Otsu thresholding
sigma_tumor: 10  # sigma for Gaussian filtering before Otsu thresholding

## thesholding method

thresholding_method: "otsu" # options are "isodata", "li", "mean", "minimum", "niblack", "otsu", "sauvola", "triangle", "yen", "local" or an integer value
window_size_thresholding: 31 # only applies for local thresholding methods


## segmentation parameters
skip_experiments: []  
segmentation_method: "common" # or "Watershed"
macrophages_small_objects: 350   # physical size of "debry" in microns^3 that will be taken out of macrophage mask
file_ext : ".tif"


# cellpose segmentation
use_gpu: False
cp_model_path: "None"
cp_output_path: "/folder/to/cp_output/"
diameter : 30
dpi: 1
min_macrophage_area: 10  # min size in pixel^2
filter_experiments: "none" # options: "none" or "annotated"
export_masks : npy # or vtk or none
resume: False
plot_properties : False
flow_threshold : 0.4 # cellpose default is 0.4
cellprob_threshold: 0.0  # cellpose default is 0.0 , TODO: unused at the moment

### 3D stitch

stitch_threshold: 0.1
anisotropy: 2.5 # TODO: check impact on segmentation, https://cellpose.readthedocs.io/en/latest/settings.html
z_axis: 0 # position of z-axis, in the cellpose documentation it is stated "segment list of images x, or 4D array - Z x nchan x Y x X"
diameter_3D: 30
min_macrophage_voxels : 100

# time series analysis

macrophage_input_path_1dpi : "/folder/to/cellpose/segmentations/"
macrophage_input_path_5dpi : "/folder/to/cellpose/segmentations/"

sample_full_hours : False
filter_conditions : ["LBT003","BT333"]

