data_folder: "/folder/to/data/"
output_folder: "/folder/to/output/"
key_file_name: "Details_imaging_data_3D.xls"


dimension: "2D"   # "2D" or "3D"
channel_tumor : 0
channel_macrophages: 1
channel_vessels: 2


substract_background: "None" # or None to skip background substraction

substract_tumor_from_macrophages: False

thresholding_method: "otsu" # options are "isodata", "li", "mean", "minimum", "niblack", "otsu", "sauvola", "triangle", "yen", "local" or an integer value
window_size_thresholding: 31 # only applies for local thresholding methods

otsu_thresholding: False  # Boolean if Otsu thresholding should be performed #TODO remove

sigma_macrophage: 1  # sigma for Gaussian filtering before Otsu thresholding
sigma_tumor: 1  # sigma for Gaussian filtering before Otsu thresholding

segmentation_method: "ilastik"  # possibilities are "ilastik" or "Thresholding"

macrophages_small_objects: 500   # physical size of "debry" in microns^3 that will be taken out of macrophage mask

export_masks : npy # or vtk or none


# cellpose segmentation
use_gpu: False
output_filename: "image_001"


